# Generated by Django 5.1.2 on 2024-10-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_eventparticipator_checkin_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipator',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
