name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        id: build
        run: |
          TAG=${{ secrets.DOCKER_USERNAME }}/scanner:$(date +%s)
          docker build . --file Dockerfile --tag $TAG
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Push the Docker image
        run: |
          docker push ${{ env.TAG }}
